### ISSUE TITLE
Add Extended Key Usages for certificate creation

### ISSUE THREAD

**Issue by OleksandrSPV** [PeculiarVentures/fortify-tools#154]
There is no way to add the extended key usages when certificate create method calls. Should be add support in @peculiar/fortify-client-core

**Comment by OleksandrSPV** [comment]
@donskov Could you please help with it?

**Comment by donskov** [comment]
@OleksandrSPV The latest version of `@peculiar/fortify-client-core` now includes a parameter that should help you to resolve the current issue.

**Comment by OleksandrSPV** [comment]
@donskov Thanks, I'll check
