### ISSUE TITLE
Remove Friendly name & Description for certificate creation

### ISSUE THREAD

**Issue by OleksandrSPV** [PeculiarVentures/fortify-tools#155]
There is no way to add Friendly name & Description when certificate create method calls. Should be add support in @peculiar/fortify-client-core

**Comment by OleksandrSPV** [comment]
@donskov Could you please help with it?

**Comment by donskov** [comment]
@OleksandrSPV Unfortunately, I don't know what certificate fields can be used to set this data. Could you please attach the screenshot of the certificate creation form and maybe @microshine could help us with it?

**Comment by donskov** [comment]
I just spoke with @microshine  and we came to the conclusion that it is also not clear what exactly to do with these fields. Let's clarify this issue with the designer.

**Comment by alexgbv** [comment]
What exactly the issue with adding fields? In which part of certificate details to put it? I'm not sure I understand.

If it's a deep problem and we can easily resolve this we can remove those fields since they are not mandatory.

**Comment by microshine** [comment]
It is possible that these fields are intended to provide additional information that can be used after the certificate request is generated. Specifically, the friendly name and description can be saved along with the generated certificate request in the client's database. This allows for further management and identification of certificates. However, this option should be optional, as it is not necessary if the client only needs the certificate request file.

From the Fortify perspective, Fortify allows setting a label for PKCS#11 objects. Here is an example:

```javascript
provider.certStorage.importCert('raw', data, {name: 'ECDSA', namedCurve: 'P-256', label: 'My Friendly Name'}, ['verify']);
```

Reference to the relevant code: https://github.com/PeculiarVentures/node-webcrypto-p11/blob/0990e44961d04e28afc80cadb5455eec4541ee8c/src/certs/csr.ts#L56

**Comment by alexgbv** [comment]
Does it mean we can leave these fields?

**Comment by microshine** [comment]
I don't know the original purpose of adding these fields, but in the context of Fortify, they don't carry much significance. I believe they can be removed.

**Comment by OleksandrSPV** [comment]
Ok folks, I'll remove these fields and close this task, thanks for help everyone.
