### ISSUE TITLE
Need add sorting on Type 

### ISSUE THREAD

**Issue by OlhaPeculiar** [PeculiarVentures/fortify-tools#176]
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/0d23188f-48d3-4cfc-82d7-3975dffc8248">

**Comment by OleksandrSPV** [comment]
@OlhaPeculiar Related to https://github.com/orgs/PeculiarVentures/projects/9/views/1?pane=issue&itemId=61553399

**Comment by OleksandrSPV** [comment]
There is only one type of certificate in list, I mean should we add this sorting by type now or we will add it when we have support for scr in list. What do you think? @donskov @OlhaPeculiar

**Comment by donskov** [comment]
@OleksandrSPV Let's add it now and close the task there.

**Comment by OleksandrSPV** [comment]
> @OleksandrSPV Let's add it now and close the task there.

Ok, I'll do.

**Comment by OleksandrSPV** [comment]
@donskov here is a PR https://github.com/PeculiarVentures/fortify-tools/pull/181

**Comment by OleksandrSPV** [comment]
> @OleksandrSPV Only the @OlhaPeculiar can close the issue because she needs to test it again.

Olga is already tested it on https://fortify-tools-2-oleksandrspv-oleksandrspvs-projects.vercel.app and told me that all works fine @donskov
