### ISSUE TITLE
Proposal: Expand UI to Display Detailed Information About Token Providers

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify-tools#187]
**Description:**
Currently, Fortify Tools displays only the token name in the list of available providers. I propose expanding the UI to include more detailed information about the token provider. This enhancement would allow users to access more information about the tokens they are using and would also provide a way to include additional token-related functionality, such as the option to refresh the session.

**Current Implementation:**
The current implementation represents such information objects as `ProviderInfoProto` and `TokenInfoProto`. You can refer to the relevant code in the following link: [ProviderInfoProto and TokenInfoProto](https://github.com/PeculiarVentures/webcrypto-local/blob/master/packages/proto/src/provider.ts).

**Benefits:**
- **Enhanced User Experience:** Users would have access to more comprehensive information about their tokens, helping them make better-informed decisions.
- **Improved Functionality:** By including more details in the UI, we can introduce additional features, such as session management directly from the token information interface.

**Example:**
As an example, the SafeNET application provides a similar feature where it displays detailed information about token providers. Below is a screenshot demonstrating how SafeNET presents this information. This could serve as a model for implementing similar functionality in Fortify Tools.

**Screenshot:**
<img width="939" alt="image" src="https://github.com/user-attachments/assets/30d97a82-b077-4f6f-9c91-f085834a706d">

<img width="786" alt="image" src="https://github.com/user-attachments/assets/8e3b4d36-5dfe-49e3-976e-e80e5e2fe79d">

**Comment by rmhrisk** [comment]
This could help with support, especially with unsupported tokens.
