### ISSUE TITLE
Missing update button for certificates on Fortify Tools Page

### ISSUE THREAD

**Issue by Kharya1337** [PeculiarVentures/fortify-tools#188]
A customer has reported an issue on the Fortify Tools page. Previously, when connecting another digital signature, the page allowed updating Windows CryptoAPI certificates. This was necessary to access the CFIA. However, the customer is now unable to find the "Update" button that was used to perform this action.

> En la pagina [Fortify Tools (fortifyapp.com)](https://tools.fortifyapp.com/) al conectar otra firma digital permitía actualizar los certificados de Windows cryptoAPI, para ingresar al CFIA, ya nos se como realizarlo ya que no aparece el equino de actualizar.

**Expected Behavior:**
The "Update" button should be present, allowing users to update the Windows CryptoAPI certificates as needed.

**Actual Behavior:**
The "Update" button is no longer visible, preventing users from updating the certificates.

CC @alexgbv @aleksandr-slobodian

**Comment by alexgbv** [comment]
@Salamandra337 Please work on that.

**Comment by microshine** [comment]
This could be implemented within the scope of https://github.com/PeculiarVentures/fortify-tools/issues/187. In addition to supporting the Refresh token functionality, it could also include features for Login and Logout functionality.

**Comment by OleksandrSPV** [comment]
Fixed here https://github.com/PeculiarVentures/fortify-tools/issues/195 and here https://github.com/PeculiarVentures/fortify-tools/issues/192 @Kharya1337
