### ISSUE TITLE
Add "Refresh certificates list" Button

### ISSUE THREAD

**Issue by OleksandrSPV** [PeculiarVentures/fortify-tools#192]
- [x] Add "Refresh certificates list" Button 
- [x] Move Import Certificate Button to New Certificate Button menu

<img width="851" alt="image" src="https://github.com/user-attachments/assets/204700ab-9dcd-4983-8112-57d4b5f943a4">

![Image](https://github.com/user-attachments/assets/656c5588-bc95-4552-832c-8332f1288b27)

**Comment by OlhaPeculiar** [comment]
<img width="1406" alt="image" src="https://github.com/user-attachments/assets/849cd1ca-8fdf-41e2-8c37-33edd46b03e0">
Done
