### ISSUE TITLE
Incorrect Certificate Profile for Code Signing

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify-tools#198]
**Description:**

Our web application allows users to create self-signed certificates by specifying a certificate profile during creation. I attempted to create a certificate using the **Code Signing** profile.

**Expected Behavior:**
The generated certificate should have the appropriate extensions and policies for Code Signing.

**Actual Behavior:**
The created certificate, however, includes extensions related to certificate authentication and lacks the necessary policies for Code Signing.

**Screenshots:**

1. **Certificate Profile Selection:**
   <img width="791" alt="image" src="https://github.com/user-attachments/assets/9420f08e-4b5e-4a7b-b166-315fcee07b0c">

2. **Generated Certificate Details:**
   <img width="869" alt="image" src="https://github.com/user-attachments/assets/84e439f0-aa22-45b8-938b-ad072b20dcbf">

**Steps to Reproduce:**
1. Navigate to the certificate creation page.
2. Select the "Code Signing" profile.
3. Generate the certificate.
4. Inspect the generated certificate's extensions and policies.

**Expected Outcome:**
The generated certificate should match the selected profile, specifically including Code Signing policies.

**Recommendation:**
Please review and ensure that all certificate generation profiles are correctly implemented and result in certificates with the appropriate extensions and policies.

**Comment by OleksandrSPV** [comment]
@microshine Here is the PR https://github.com/PeculiarVentures/fortify-tools/pull/204
