### ISSUE TITLE
Unclear behavior of the system for the user when creating Create Self-signed certificate.

### ISSUE THREAD

**Issue by OlhaPeculiar** [PeculiarVentures/fortify-tools#206]
When creating certificates, validation should be added to ensure the certificate names are unique, along with a user-friendly notification informing users that certificate names must be different.

https://github.com/user-attachments/assets/78fa88ee-845c-4f29-be51-a79e3d20488f

**Comment by donskov** [comment]
@OlhaPeculiar I'm not really sure, but the certificate names might be the same. This is not an error.

**Comment by OlhaPeculiar** [comment]
I cannot create a certificate with the same email, for example (for document/code  signing, S/MiME) in Create Self-signed certificate. Look at video, it could be different error, but User can't add  Create Self-signed certificate for now 
@donskov

**Comment by donskov** [comment]
Ah, agree @OlhaPeculiar. 
@OleksandrSPV Please check why this happens and let's try to show the text of the error if it is informative.

**Comment by OleksandrSPV** [comment]
> Ah, agree @OlhaPeculiar. @OleksandrSPV Please check why this happens and let's try to show the text of the error if it is informative.

Sure, I'll check, thanks @OlhaPeculiar @donskov

**Comment by microshine** [comment]
Errors with codes starting with CKR_ (such as CKR_FUNCTION_FAILED) are coming from PKCS#11 modules. In these cases, we are unable to retrieve additional information because the modules only return the error code. Provider implementations may also vary: some may produce this error, while others may not, or may return a different error code altogether.

**Comment by OleksandrSPV** [comment]
@microshine and I realised if remove serialNumber: 01, certificate created successfully 
https://github.com/PeculiarVentures/fortify-webcomponents/blob/b5899f5eb228487961646eab9fc86919c1ed90f3/packages/client-core/src/fortify_api.ts#L719

https://github.com/PeculiarVentures/x509/blob/541460b83ad99096b45e888f47dda512809551e8/src/x509_cert_generator.ts#L133
@donskov Why do we use the same id (01)?

**Comment by microshine** [comment]
As far as I remember, macOS Keychain cannot store two certificates with the same name and serial number. If I'm not mistaken, I encountered this issue when creating SSL certificates for Fortify.

**Comment by donskov** [comment]
> @microshine and I realised if remove serialNumber: 01, certificate created successfully https://github.com/PeculiarVentures/fortify-webcomponents/blob/b5899f5eb228487961646eab9fc86919c1ed90f3/packages/client-core/src/fortify_api.ts#L719
> 
> https://github.com/PeculiarVentures/x509/blob/541460b83ad99096b45e888f47dda512809551e8/src/x509_cert_generator.ts#L133 @donskov Why do we use the same id (01)?
> 
> <img alt="image" width="1438" src="https://private-user-images.githubusercontent.com/129727832/364799389-80ebe7d1-07e9-4ddf-bb61-f0222c670a67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDcwODcsIm5iZiI6MTcyNTU0Njc4NywicGF0aCI6Ii8xMjk3Mjc4MzIvMzY0Nzk5Mzg5LTgwZWJlN2QxLTA3ZTktNGRkZi1iYjYxLWYwMjIyYzY3MGE2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNDMzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzZmMGRhZGU0MDY2YTkwODgxNGFmNzEzMTM5YWJlYTRjMGYxMjMwOTFiYTk4OTllYzBhM2E2N2U4MzJkMTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wEYGKKvBD80yG7nqYRvnu6GJisObffB7PUVvllWleqg">

I removed the static serial number value. Please update deps.

**Comment by OleksandrSPV** [comment]
@OlhaPeculiar Please check https://fortify-tools.vercel.app, thanks

**Comment by OlhaPeculiar** [comment]
Done
