### ISSUE TITLE
Fortify app not running on Windows 7 (32-bit) Virtual Machine

### ISSUE THREAD

**Issue by defacto64** [PeculiarVentures/fortify-tools#41]
On a Windows 7 (32-bit) virtual machine, hosted by VMware Workstation, the Fortify app does not run.
Trying to run it causes the following error message to appear:
![image](https://user-images.githubusercontent.com/1590003/83123976-dded0e00-a0d5-11ea-8ce4-68e6744827e6.png)

**Comment by defacto64** [comment]
Of course, I made sure to have downloaded the 32-bit version of the Fortify installer for Windows.

**Comment by microshine** [comment]
What version of Fortify is?

**Comment by defacto64** [comment]
The latest available, that is 1.0.21, downloaded from https://fortifyapp.com/

**Comment by donskov** [comment]
Hello @defacto64. Could you try to use the new version from https://fortifyapp.com/?

**Comment by defacto64** [comment]
Hello Dmitriy,

I have just tried with **fortify-win32-x86-v1.5.0.msi**, but the situation is unchanged; the installation works, but when I try to launch Fortify I get the following error message:

![image](https://user-images.githubusercontent.com/1590003/100317784-3043b480-2fbd-11eb-9404-dc3f424870cb.png)
