### ISSUE TITLE
Frozen on CKR_PIN_LEN_RANGE error

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify-tools#60]
![image](https://user-images.githubusercontent.com/7333669/119622884-46b5b600-be10-11eb-9e68-c5e2ac2c1fd0.png)

![image](https://user-images.githubusercontent.com/7333669/119622809-2b4aab00-be10-11eb-80d6-a38a340a128c.png)

Steps:
- insert token
- select provider with the inserted token
- enter PIN larger than `TokenInfo::maxPinValue`

**Comment by donskov** [comment]
@microshine Added correct dialog for "CKR_PIN_LEN_RANGE" error. Please check.

**Comment by donskov** [comment]
@microshine Could we close it?
