### ISSUE TITLE
Not clear why buttons are disabled

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify-tools#61]
![image](https://user-images.githubusercontent.com/7333669/119626671-225bd880-be14-11eb-9628-8c5f5757e94c.png)

Suggestions:
- Add tooltip `This is a read-only token so this operation is disabled.`
- Show information about the token which says that it's in read-only mode and hide edit buttons

@alexgbv Could you suggest a UI solution?

**Comment by alexgbv** [comment]
I would suggest something like that:
![image](https://user-images.githubusercontent.com/39085824/119633794-c2b4fb80-be1a-11eb-910f-efecbf98b616.png)
https://www.figma.com/file/5VYGSxMKzoV1BgewYKFKSd/Fortify?node-id=1384%3A1393

**Comment by donskov** [comment]
@alexgbv Thanks for the solution. But, I think is not perfect. When you choose `readOnly` provider after not `readOnly` most UI elements will change their position. It will look like ping pong.

**Comment by alexgbv** [comment]
@donskov Read-only token is the same stuff as read-only provider here?

**Comment by donskov** [comment]
@alexgbv Yes.

**Comment by alexgbv** [comment]
Ok, so that you told above make sense?

**Comment by alexgbv** [comment]
How about that?
![Uploading image.png…]()

**Comment by donskov** [comment]
@alexgbv I like it.

@microshine What do you think?

**Comment by microshine** [comment]
I like it too. Let's do it

**Comment by donskov** [comment]
@microshine Added provider readOnly indicator. Please check.

**Comment by microshine** [comment]
It works

![image](https://user-images.githubusercontent.com/7333669/119856830-b2d11080-bf1b-11eb-9ddc-b5d0d6a65fb8.png)
