### ISSUE TITLE
Javascript error after entering YubiKey PIN

### ISSUE THREAD

**Issue by kmb64** [PeculiarVentures/fortify-tools#65]
The following error surfaces when entering the YubiKey PIN.

Looks like it would be caused by this recent commit: 

https://github.com/PeculiarVentures/fortify-tools/commit/a072594828dce9f1f30ff82a0245aa4ff7992f60#diff-82612db8f32ac3ab655fc3ee29a1e9334c9c22aae60de4ff0dba8d4b5b6c2b67R488

See screenshots below.

Fortify version: 1.3.4
OS: Windows
Browser: Chrome Version 91.0.4472.124 (Official Build) (32-bit)

![image (4)](https://user-images.githubusercontent.com/1438484/124699531-4db30680-df2e-11eb-86f2-e2203e9f5b8d.png)
![image (5)](https://user-images.githubusercontent.com/1438484/124699534-50156080-df2e-11eb-8577-9030d8cda307.png)

**Comment by rmhrisk** [comment]
Can you install latest version and try to reproduce?

**Comment by donskov** [comment]
@kmb64 Thanks for the report. I made changes and deployed them. Please check again.

**Comment by kmb64** [comment]
Thank you @donskov all good now.

**Comment by rmhrisk** [comment]
@kmb64 would love to hear about your use case; can mail me at ryan at peculiarventures if you can discuss it.
